name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: '9.0.4'
    - uses: DeLaGuardo/setup-clojure@1.0
      with:
        tools-deps: '1.10.1.469'
    - run: clojure -m jameslintaylor.doctest
    - run: clojure -Acov
